Revert "⚗️ Tester ubuntu-slim-runner for deploy til dev"
Feiler med:
  /usr/bin/docker build -t b2f55e:bd15c9e0d9fa4686b3862a3331332276 -f "/home/runner/work/_actions/nais/deploy/v2/actions/deploy/Dockerfile" "/home/runner/work/_actions/nais/deploy/v2/actions/deploy"
  ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Fordi nais deploy bygger et image, åpenbart..

This reverts commit 50c374f70557669988ec1a08f511c9fcbe576685.